# Don't run as root.
sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

# Build matrix.
matrix:
  include:
    - env: GHCVER=8.8.3 STACK_YAML=stack.yaml
      compiler: GHC-8.8.3
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.8.3

    - env: GHCVER=8.6.5 STACK_YAML=stack-8.6.yaml
      compiler: GHC-8.6.5
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.6.5

    - env: GHCVER=8.4.2 STACK_YAML=stack-8.4.yaml
      compiler: GHC-8.4.2
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.4.2

    - env: GHCVER=8.2.2 STACK_YAML=stack-8.2.yaml
      compiler: GHC-8.2.2
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.2.2

    - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.yaml
      compiler: GHC-8.0.2
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-8.0.2

    - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
      compiler: GHC-7.10.3
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - ghc-7.10.3

# Download and unpack stack.
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# Avoid timeouts.
install:
  - travis_wait stack --no-terminal --skip-ghc-check setup
  - travis_wait stack --no-terminal --skip-ghc-check test --only-snapshot

# Run the tests.
script:
  - stack --no-terminal --skip-ghc-check test --fast
