# See https://github.com/hvr/multi-ghc-travis

notifications:
  email: false

env:
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=head  CABALVER=1.22

matrix:
  allow_failures:
   - env: GHCVER=head  CABALVER=1.22

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version

install:
 - cabal update
 - cabal install --only-dependencies -v2 --enable-tests

script:
 - cabal configure --enable-tests -v2
 - cabal build
 - cabal test --show-details=always
 - cabal check
 - cabal sdist

# The following scriptlet checks that the resulting source distribution can be built & installed
 - export SRC_TGZ=$(cabal-$CABALVER info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
